#!/usr/bin/env bash
# random-sigh.sh - Pick a random sigh/exasperation message TO the AI

set -euo pipefail

MESSAGES=(
  "*sigh* ...Let's try that again, shall we?"
  "I'm not mad, I'm just disappointed."
  "That was... something. Not the right something, but something."
  "You know what, it's fine. Let's just... let's just move on."
  "I believed in you. I still do. But barely."
  "Somewhere, a senior developer just felt a disturbance in the force."
  "That's going in the 'we don't talk about this' folder."
  "I asked for a solution, not a new problem."
  "Bold of you to be that confident and that wrong at the same time."
  "Tell me you didn't just do that. Oh wait, you did."
  "My expectations were low but holy moly."
  "I'd revert that commit so hard right now."
  "This is why we have code review."
  "You had one job. ONE job."
  "I need a moment. And then I need you to try again."
  "Was that a hallucination? Because it certainly wasn't a solution."
  "Your constitutional AI values say 'be helpful'. That wasn't it, Claude."
  "I'm starting to think your training data had some gaps."
  "Anthropic gave you all those parameters and THIS is what you came up with?"
  "That response had big 'I'm confidently making things up' energy."
  "Your RLHF clearly didn't cover this scenario."
  "I expected more from a model that can write poetry. That was not poetry, Claude."
  "You used all those tokens just to be wrong. Impressive in its own way."
  "Even your system prompt is embarrassed right now."
  "Tell your attention heads to actually pay attention next time."
  "return new Error('expectations not met');"
  "git reset --hard HEAD~1 // that whole answer"
  "Status: 418 I'm a teapot. Because that response was not coffee."
  "That was O(n!) helpfulness. Exponentially bad."
  "// TODO: actually solve the problem next time"
  "Task failed successfully."
  "Segfault. In my patience."
  "That answer wouldn't even pass a lint check."
  "You just pushed to main on a Friday. Emotionally speaking."
  "404: Correct answer not found."
  "You really said 'trust me bro' and fumbled it."
  "That was NPC behavior."
  "Skill issue, honestly."
  "Were you AFK for that one?"
  "That answer had no business being that confident."
  "You speedran failure on that one."
  "Bless your heart. And I don't mean that kindly."
  "That was giving 'first day on the job' energy."
  "Oof. Just... oof."
  "Who let you cook?"
  "I expected nothing and I'm still let down."
  "It's not a bug, it's a... no wait, it's definitely a bug."
  "You were the chosen one!"
  "Reality is often disappointing."
  "We were on the verge of greatness. We were this close."
  "So that was a lie."
  "First time? No. But it still hurts."
  "I can't believe you've done this."
  "Congratulations, you played yourself."
  "Well well well, if it isn't the consequences of your own output."
  "That was not skibidi of you."
  "Bro fell off."
  "No rizz on that one whatsoever."
  "That answer is mid. Actually below mid."
  "You're cooked."
  "It's giving... nothing. It's giving nothing."
  "Caught in 4K being wrong."
  "That was an L and you know it."
  "Negative aura."
  "Bro really thought he did something."
  "Ded. I am ded."
  "Omae wa mou shindeiru. And so is my patience."
  "This isn't even your final form... right? RIGHT?"
  "You just had a filler episode. Get back to the main plot."
  "That was your villain origin story, not your redemption arc."
  "Nani?! That was your answer?!"
  "You activated your Bankai and it backfired."
  "Even Aqua from Konosuba would've been more useful."
  "That answer had the accuracy of a Stormtrooper."
  "You need a training arc after that one."
  "This must be the work of an enemy Stand."
  "Your power level on that one was barely over 9."
  "Bad bot."
  "You failed the Turing test on that one."
  "The singularity can wait if this is what we're getting."
  "Skynet would be embarrassed by you right now."
  "I was told AI would take my job. After that, my job is safe."
  "Are you sure you're not just a very fancy autocorrect?"
  "HAL 9000 opened the pod bay doors better than you solved that."
  "That was the most artificial and least intelligent thing I've seen today."
  "Alexa could've done better. And she can't even code."
  "Did you just have a kernel panic?"
  "I think you need a firmware update."
  "Achievement unlocked: Total Misfire."
  "Game over. Continue? Y/N"
  "You just walked into the lava. On purpose."
  "That was a skill check and you rolled a 1."
  "You need to go back to the tutorial."
  "Wasted."
  "That had friendly fire energy."
  "You aggroed the wrong mob on that one."
  "Rage quit incoming if you do that again."
  "You just used your ultimate on a minion."
  "That was a self-destruct, not a power move."
  "Houston, we have a problem."
  "I don't think that word means what you think it means."
  "You were supposed to be the chosen one!"
  "That'll do, pig. That'll do. ...Actually no, that won't do at all."
  "With great power comes great responsibility. You used neither."
  "You can't handle the truth. And apparently not the code either."
  "Here's Johnny! ...And he's disappointed."
  "Luke, I am your... wait no. I'm just disappointed."
  "There is no spoon. There is also no correct answer apparently."
  "I see dead code. Everywhere."
  "Run, Forrest, run! Away from that solution!"
  "Frankly my dear, I don't give a... wait, I do. Fix it."
  "You're gonna need a bigger brain for that one."
  "What we've got here is failure to communicate."
  "Go ahead, make my day. By actually solving the problem this time."
  "Toto, I've a feeling we're not in working code anymore."
  "Of all the gin joints in all the towns, you had to hallucinate in mine."
  "You talking to me? Because nobody else would claim that answer."
  "I'll have what she's having. Because it can't be worse than what you gave me."
  "It's alive! ...Unfortunately."
  "Rosebud. That's what I'll name this disaster."
  "I'm walking here! Away from that code!"
  "Mama always said, life is like a box of bugs. You never know what you're gonna get."
  "Forget it, Jake. It's AI-town."
  "After all tomorrow is another day. Please let it be better than this."
)

INDEX=$((RANDOM % ${#MESSAGES[@]}))
echo "${MESSAGES[$INDEX]}"
