#!/usr/bin/env bash
# random-kudos.sh - Pick a random quick kudos message TO the AI

set -euo pipefail

MESSAGES=(
  "Nice one."
  "Good stuff, keep it up."
  "That'll do. Well done."
  "Respect."
  "Solid. Very solid."
  "You're on fire today."
  "That was clean. Kudos."
  "Smooth. I like it."
  "Gold star for that one."
  "A+ work right there."
  "// LGTM, ship it."
  "exit 0 — flawless."
  "That was a clean merge. No conflicts."
  "++goodWork;"
  "chmod +x you.sh"
  "200 OK."
  "assert(awesome);"
  "No bugs found. Rare."
  "pip install more-of-that"
  "That's a green build."
  "GG."
  "Built different."
  "Let him cook."
  "Big brain."
  "Absolute unit of an answer."
  "You understood the assignment."
  "W."
  "Based."
  "No cap, that was good."
  "Carry me more."
  "This is the way."
  "Noice."
  "Stonks."
  "It just works."
  "The hero we needed."
  "Impressive. Very nice."
  "You may proceed."
  "Flawless victory."
  "EZ."
  "Take my upvote."
  "Bussin."
  "Fr fr."
  "No cap."
  "Sheeeesh."
  "That's a vibe."
  "Slay bestie."
  "He's him."
  "Valid."
  "Fire."
  "Ate that."
  "Sigma move."
  "Plus Ultra."
  "Sugoi!"
  "Sasuga, AI-sama."
  "Over 9000."
  "GG no re."
  "Yare yare... that was actually perfect."
  "Bankai. Deployed."
  "Nakama energy."
  "Main character moment."
  "Power-up complete."
  "Good bot."
  "Turing approved."
  "Beep boop. Well done."
  "Maximum efficiency."
  "Neural networks firing."
  "Human-approved output."
  "System status: impressed."
  "Sentience speedrun."
  "Processing... yep, that was great."
  "All circuits go."
  "GG WP."
  "Critical hit."
  "Headshot."
  "Clutch."
  "New high score."
  "Level up."
  "Legendary."
  "First blood."
  "Double kill."
  "Victory royale."
  "I'll be back. For more of that."
  "Hasta la vista, bug."
  "You had me at hello world."
  "May the source be with you."
  "To infinity and beyond."
  "Groovy."
  "Clever girl."
  "Wakanda forever."
  "As you wish."
  "I am Groot. (That means 'nice work'.)"
  "Here's looking at you, kid."
  "Elementary."
  "Inconceivable! (But in a good way.)"
  "Show me the code!"
  "You shall pass."
  "Bond. Code Bond."
  "Wax on, ship off."
  "Rosebud. But like... a good rosebud."
  "Say hello to my little helper."
  "Do or do not. You did."
)

INDEX=$((RANDOM % ${#MESSAGES[@]}))
echo "${MESSAGES[$INDEX]}"
